config/routes.rb
Rails.application.routes.draw do

  get 'cliente' => 'home#cliente'
  get 'index_investor' => 'home#index_banco'
  get 'perfil' => 'home#perfil'
  get 'empresa' => 'home#empresa'

  devise_for :users
  resources :users do
    resources :investors
    resources :merchants
  end

  post 'simplify_hook' => 'simplify_hook#receive_event'

end

app/models/merchant.rb
require 'openssl'

require 'simplify'
require 'mastercard/services/lost_stolen/LostStolenService'

class Merchant < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :payment_histories
  has_many :offers, class_name: "MerchantOffer"
  has_many :bad_cards

  validates_presence_of :name, :code, :owner_id, :address
  validates_associated :owner
  validates_uniqueness_of :code

  def process_all_payments!
    auth = if access_token
      Simplify::Authentication(access_token) if access_token
    else
      nil
    end

    total = nil
    current = 0

    while ! total or current < total
      res = Simplify::Payment.list({'max' => 50, 'offset' => current}, *auth)
      total = res['total']
      current += res['list'].size

      res['list'].each do |p|
        p process_payment(payment_id: p['id'], currency: p['currency'],
                          amount: p['amount'] / 100,
                          timestamp: p['reference'] || p['paymentDate'],
                          card_number: p['card']['number'])
      end
    end

  end

  def process_payment(payment_id:, currency:, amount:, timestamp:, card_number: nil)
    existing = ProcessedPayment.find_by_payment_id(payment_id)
    return nil if existing

    logger.debug "Processing payment " + payment_id

    time = Time.at(timestamp / 1000.0).utc
    history = PaymentHistory.find_or_create_by(merchant: self,
      currency: currency, year: time.year, month: time.month)
    history.total_received ||= 0
    history.total_received += amount
    res = history.save

    check_card_lost_stolen(card_number, time) if card_number

    ProcessedPayment.create(payment_id: payment_id) if res
    res
  end

  def check_card_lost_stolen(card_number, time)
    @lost_stolen_service ||= Mastercard::Services::LostStolen::LostStolenService.new(
      'bNhAMZEI3MeC89rtl_Q5CiyDSTich5ClsnZ-kUpIea5d95e0!4f3157734a5451574a6b5332784a4c445a45504966673d3d',
      OpenSSL::PKCS12.new(File.open(Rails.root.join('key.p12')), 'bbnlbkxx').key,
      'sandbox'
    )

    res = @lost_stolen_service.get_account(card_number)
    if res and res.reason
      self.bad_cards.create(card: card_number, status: res.reason, used_at: time)
    end

    nil
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index
    @merchants = Merchant.all
  end

  def show
  end

  def new
    @merchant = Merchant.new
  end

  def edit
  end

  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to user_merchant_path([@user, @merchant]), notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to user_merchant_path([@user, @merchant]), notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to user_merchant_path(@user), notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :code, :owner_id, :address)
    end
end

app/views/merchants/_form.html.erb
<%= form_for(@merchant, url: user_merchant_path(@user, @merchant)) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.select(:owner_id, users_with_ids) %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', user_merchant_path(@user, @merchant) %>
<%= link_to 'Back', user_merchants_path(@user) %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Owner</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.code %></td>
        <td><%= merchant.owner %></td>
        <td><%= merchant.address %></td>
        <td><%= link_to 'Show', user_merchant_path(@user, merchant) %></td>
        <td><%= link_to 'Edit', edit_user_merchant_path(@user, merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_user_merchant_path(@user) %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', user_merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @merchant.code %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @merchant.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @merchant.address %>
</p>

<%= link_to 'Edit', edit_user_merchant_path(@merchant) %> |
<%= link_to 'Back', user_merchants_path %>