config/routes.rb
Rails.application.routes.draw do

  get 'cliente' => 'home#cliente'
  get 'index_investor' => 'home#index_banco'
  get 'perfil' => 'home#perfil'
  get 'empresa' => 'home#empresa'

  devise_for :users
  resources :users do
    resources :investors
    resources :merchants
  end

  post 'simplify_hook' => 'simplify_hook#receive_event'

end

app/models/investor.rb
class Investor < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :offers, class_name: "InvestorOffer"

  validates_presence_of :name, :code, :owner_id
  validates_associated :owner
  validates_uniqueness_of :code
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor,  only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index
    @investors = Investor.all
  end

  def show
  end

  def new
    @investor = Investor.new
  end

  def edit
  end

  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to user_investor_path(@user, @investor), notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to user_investor_path(@user, @investor), notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to user_investor_path(@user), notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investor_params
      params.require(:investor).permit(:name, :code, :owner_id)
    end
end

app/views/investors/_form.html.erb
<%= form_for(@investor, url: user_investor_path(@user.id, @investor)) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.collection_select(:owner_id, User.order(:name), :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing Investor</h1>

<%= render 'form' %>

<%= link_to 'Show', user_investor_path(@user, @investor) %>
<%= link_to 'Back', user_investors_path(@user) %>

app/views/investors/index.html.erb
<section class="wrapper site-min-height">

    <div class="row mt">
    <div class="col-lg-12">
                <div class="form-panel">                                
            <div data-role="main" class="ui-content">
          <div class="col-lg-6">
            <div data-role="rangeslider">
        <label for="price-min"><strong>Faturamento total (mil):</strong></label>
        <input type="range" name="price-min" id="price-min" value="200" min="0" max="10000">
        <label for="price-max"><strong>Faturamento total (mil):</strong></label>
        <input type="range" name="price-max" id="price-max" value="4000" min="0" max="10000">
      </div></div>
    <div class="col-lg-6">
    <div data-role="rangeslider">
        <label for="price-min"><strong>Movimento no cartão (mil):</strong></label>
        <input type="range" name="price-min" id="price-min" value="200" min="0" max="10000">
        <label for="price-max"><strong>Movimento no cartão (mil):</strong></label>
        <input type="range" name="price-max" id="price-max" value="4000" min="0" max="10000">
      </div></div>


  <div class="col-lg-6">
            <div data-role="rangeslider">
        <label for="price-min"><strong>Prazo (dias):</strong></label>
        <input type="range" name="price-min" id="price-min" value="30" min="0" max="200">
        <label for="price-max"><strong>Prazo (dias):</strong></label>
        <input type="range" name="price-max" id="price-max" value="90" min="0" max="200">
      </div></div>
    <div class="col-lg-6">
    <div data-role="rangeslider">
        <label for="price-min"><strong>Valor da Carteira (mil):</strong></label>
        <input type="range" name="price-min" id="price-min" value="200" min="0" max="10000">
        <label for="price-max"><strong>Valor da Carteira (mil):</strong></label>
        <input type="range" name="price-max" id="price-max" value="3000" min="0" max="10000">
      </div></div>

  </div>

            
            <div class="col-lg-6">
            <select class="form-control">
              <option>Ramo de Atividade</option>
              <option>Artigos esportivos</option>
              <option>Bares</option>
              <option>Bebidas</option>
              <option>Brinquedos</option> 
              <option>Computadores</option> 
              <option>Equipamentos Industriais</option>
              <option>Hotelaria</option>
              <option>Internet</option>
              <option>Imobiliarias</option>
              <option>Restaurantes</option>
              <option>Varejo</option>
            </select>
            </div>
            <div class="col-lg-6">
            <select class="form-control">
              <option>Estado</option>
              <option>Acre</option>
              <option>Alagoas</option>
              <option>Amapá</option>
              <option>Amazonas</option>
              <option>Bahia</option>  
              <option>Ceará</option>  
              <option>Espirito Santo</option>
              <option>Goiás</option>
              <option>Mato Grosso</option>
              <option>Minas Gerais</option>             
            </select>
            </div>
            <br/><br/><hr>
        
        
        
                </div><!-- /form-panel -->
              </div><!-- /col-lg-12 -->

    <br/><br/>

                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            
                              <thead>
                              <tr>
                                  <th><i class="fa fa-bullhorn"></i> Empresa</th>
                                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> Atividade</th>
           <th><i class=" fa fa-globe"></i> Estado</th>
        <th><i class="fa fa-money"></i> Faturamento/Ano</th>
                                  <th><i class="fa fa-credit-card"></i> Carteira Recebíveis</th>
                                  <th><i class=" fa fa-edit"></i> Prazo Médio</th>
                                 
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td><a href="basic_table.html#">Ponto do Pão</a></td>
                                  <td class="hidden-phone">Padaria</td>
           <td>São Paulo </td>
        <td>R$ 320.000 </td>
                                  <td>R$ 120.000 </td>
                                  <td><span class="label label-danger label-mini">92 dias</span></td>
                                 
                              </tr>
                              <tr>
                                  <td>
                                      <a href="basic_table.html#">
                                          Casa da Esfiha
                                      </a>
                                  </td>
                                  <td class="hidden-phone">Restaurante</td>
        <td>Santa Catarina </td>
           <td>R$ 450.000 </td>
                                  <td>R$ 250.000 </td>
                                  <td><span class="label label-warning label-mini">65 dias</span></td>
                                
                              </tr>
                              <tr>
                                  <td>
                                      <a href="basic_table.html#">
                                          Centauro
                                      </a>
                                  </td>
                                  <td class="hidden-phone">Materiais Esportivos</td>
        <td>Rio de Janeiro </td>
          <td>R$ 4.300.000 </td>
                                  <td>R$ 1.300.000 </td>
                                  <td><span class="label label-success label-mini">25 dias</span></td>
                                 
                              </tr>
                              <tr>
                                  <td>
                                      <a href="basic_table.html#">
                                          Americanas
                                      </a>
                                  </td>
                                  <td class="hidden-phone">Varejo Online</td>
          <td>São Paulo</td>
           <td>R$ 15.203.000 </td>
                                  <td>R$ 4.203.000 </td>
                                  <td><span class="label label-success label-mini">45 dias</span></td>
                                  
                              </tr>
                              <tr>
                                  <td><a href="basic_table.html#">Granja Viana</a></td>
                                  <td class="hidden-phone">Produção de Alimentos</td>
          <td>Minas Gerais </td>
            <td>R$ 2.550.000 </td>
                                  <td>R$ 750.000 </td>
                                  <td><span class="label label-warning label-mini">60 dias</span></td>
                                 
                              </tr>
    
        <tr>
                                  <td><a href="basic_table.html#">Pão de Açucar</a></td>
                                  <td class="hidden-phone">Varejo de Alimentos</td>
          <td>São Paulo </td>
            <td>R$ 22.550.000 </td>
                                  <td>R$ 5.750.000 </td>
                                  <td><span class="label label-success label-mini">20 dias</span></td>
                                 
                              </tr>

        <tr>
                                  <td><a href="basic_table.html#">Dpaschoal</a></td>
                                  <td class="hidden-phone">Serviços Automotivos</td>
          <td>Paraná </td>
            <td>R$ 2.550.000 </td>
                                  <td>R$ 950.000 </td>
                                  <td><span class="label label-success label-mini">28 dias</span></td>
                                 
                              </tr>

        <tr>
                                  <td><a href="basic_table.html#">Apple</a></td>
                                  <td class="hidden-phone">Computadores</td>
          <td>São Paulo </td>
            <td>R$ 32.550.000 </td>
                                  <td>R$ 13.331.000 </td>
                                  <td><span class="label label-warning label-mini">55 dias</span></td>
                                 
                              </tr>



                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->


  
          </section>
      </section>

app/views/investors/new.html.erb
<h1>New Investor</h1>

<%= render 'form' %>

<%= link_to 'Back', user_investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @investor.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @investor.code %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @investor.owner %>
</p>

<%= link_to 'Edit', edit_user_investor_path(@investor) %> |
<%= link_to 'Back', user_investors_path %>